Simplify it per the docs

diff --git a/kerl b/kerl
--- a/kerl
+++ b/kerl
@@ -1263,34 +1263,23 @@ _do_build() {
     fi
 
     if [ -n "$KERL_RELEASE_TARGET" ]; then
-        kerl_release_target_sub_folder=
-        r_type_known=
         for r_type in $KERL_RELEASE_TARGET; do
-            r_type_known=true
-            kerl_release_target_sub_folder=
             case $r_type in
-            opt | debug)
-                kerl_release_target_sub_folder=
-                ;;
-            gcov | gprof | valgrind | asan | lcnt)
-                kerl_release_target_sub_folder=/erts/emulator
-                ;;
-            *)
-                r_type_known=false
-                warn "runtime type '$r_type' is invalid!"
-                ;;
-            esac
-            if [ "${r_type_known}" = "true" ]; then
+            opt | gcov | gprof | debug | valgrind | asan | lcnt)
                 notice "Also building for Erlang/OTP $1 ($2) $r_type VM; please wait..."
-                if ! cd "$ERL_TOP${kerl_release_target_sub_folder}"; then
-                    fail_do_build "couldn't cd into $ERL_TOP${kerl_release_target_sub_folder}" "$2" "$1"
+                if ! cd "$ERL_TOP/erts/emulator"; then
+                    fail_do_build "couldn't cd into $ERL_TOP/erts/emulator" "$2" "$1"
                     return 1
                 fi
-                if ! log_build_cmd "make TYPE=$r_type ERL_TOP=$ERL_TOP"; then
+                if ! log_build_cmd "make $r_type ERL_TOP=$ERL_TOP"; then
                     fail_do_build "build of '$r_type' VM failed." "$2" "$1"
                     return 1
                 fi
-            fi
+                ;;
+            *)
+                warn "runtime type '$r_type' is invalid!"
+                ;;
+            esac
         done
     fi
 }
@@ -1745,7 +1734,7 @@ do_install() {
         opt | debug)
             notice "Installing Erlang/OTP $rel ($build_name) ${r_type} VM in $absdir..."
             cd "$ERL_TOP" || exit_install
-            if ! log_install_cmd "TYPE=$r_type ERL_TOP=$ERL_TOP ./otp_build release -a $absdir && cd $absdir && ./Install $INSTALL_OPT $absdir"; then
+            if ! log_install_cmd "TYPE=$r_type ERL_TOP=$ERL_TOP ./otp_build release -a $absdir"; then
                 show_install_logfile "install Erlang/OTP $rel ($build_name) of type '$r_type', in $absdir, failed"
                 exit_install
             fi
