Install user_default

diff --git a/kerl b/kerl
--- a/kerl
+++ b/kerl
@@ -1145,8 +1145,13 @@ install_docsh() {
         cat $DOCSH_DIR/templates/dot.erlang > $HOME/.erlang
     fi
     ## Install docsh user_default
-    echo "not done yet, fail intentionally"
-    exit 1
+    if [ -f $DOCSH_DIR/user_default.beam ]; then
+        echo "Couldn't install $DOCSH_DIR/user_default.beam - the file already exists"
+        : rm -Rf "$DOCSH_DIR"
+        exit 1
+    else
+        erlc -I $DOCSH_DIR/include -o $DOCSH_DIR/ ~/work/erszcz/docsh/templates/user_default.erl
+    fi
 }
 
 download_manpages()
