wx-20.3: that should fix it

diff --git a/kerl b/kerl
--- a/kerl
+++ b/kerl
@@ -670,6 +670,28 @@ _do_build() {
     cd "$ERL_TOP" || exit 1
     LOGFILE="$KERL_BUILD_DIR/$2/otp_build_$1.log"
 
+    # Set configuation flags given applications white/black lists
+    if [ -n "$KERL_CONFIGURE_APPLICATIONS" ]; then
+        for app in $KERL_CONFIGURE_APPLICATIONS; do
+            case "$KERL_CONFIGURE_OPTIONS" in
+                *"--with-$app"*)
+                    echo "Option '--with-$app' in KERL_CONFIGURE_OPTIONS is superfluous" ;;
+                *)
+                    KERL_CONFIGURE_OPTIONS="$KERL_CONFIGURE_OPTIONS --with-$app" ;;
+            esac
+        done
+    fi
+    if [ -n "$KERL_CONFIGURE_DISABLE_APPLICATIONS" ]; then
+        for app in $KERL_CONFIGURE_DISABLE_APPLICATIONS; do
+            case "$KERL_CONFIGURE_OPTIONS" in
+                *"--without-$app"*)
+                    echo "Option '--without-$app' in KERL_CONFIGURE_OPTIONS is superfluous" ;;
+                *)
+                    KERL_CONFIGURE_OPTIONS="$KERL_CONFIGURE_OPTIONS --without-$app" ;;
+            esac
+        done
+    fi
+
     # Check to see if configuration options need to be stored or have changed
     TMPOPT="/tmp/kerloptions.$$"
     echo "$CFLAGS" >"$TMPOPT"
@@ -726,18 +748,18 @@ _do_build() {
 
     if [ -n "$KERL_CONFIGURE_APPLICATIONS" ]; then
         find ./lib -maxdepth 1 -type d -exec touch -f {}/SKIP \;
-        for i in $KERL_CONFIGURE_APPLICATIONS; do
-            if ! rm ./lib/"$i"/SKIP; then
-                echo "Couldn't prepare '$i' application for building"
+        for app in $KERL_CONFIGURE_APPLICATIONS; do
+            if ! rm ./lib/"$app"/SKIP; then
+                echo "Couldn't prepare '$app' application for building"
                 list_remove builds "$1 $2"
                 exit 1
             fi
         done
     fi
     if [ -n "$KERL_CONFIGURE_DISABLE_APPLICATIONS" ]; then
-        for i in $KERL_CONFIGURE_DISABLE_APPLICATIONS; do
-            if ! touch -f ./lib/"$i"/SKIP; then
-                echo "Couldn't disable '$i' application for building"
+        for app in $KERL_CONFIGURE_DISABLE_APPLICATIONS; do
+            if ! touch -f ./lib/"$app"/SKIP; then
+                echo "Couldn't disable '$app' application for building"
                 exit 1
             fi
         done
